# Generated by Django 3.2.2 on 2021-05-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20210527_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postwall',
            name='like',
        ),
        migrations.AddField(
            model_name='postwall',
            name='like',
            field=models.ManyToManyField(to='Profile.LikePost'),
        ),
    ]
