# Generated by Django 3.2.2 on 2021-05-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20210527_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postwall',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, to='Profile.LikePost'),
        ),
    ]
