# Generated by Django 3.2 on 2021-04-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210426_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userPhotos',
            field=models.ImageField(blank=True, upload_to='userPhotos'),
        ),
    ]
