# Generated by Django 3.2 on 2021-04-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_userphotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userPhotos',
            field=models.ImageField(upload_to='userPhotos'),
        ),
    ]
